CREATE OR REPLACE VIEW "CONT_POR_USUARIO" AS 
SELECT ID,
	NOME,
	COUNT(ID) as CONTAGEM
FROM(
		SELECT CBBTABLE.cbb_usu as ID,
			USERTABLE.usr_nome as NOME
		FROM "cleaned-cbb" AS CBBTABLE
			INNER JOIN "cleaned-usuario" as USERTABLE ON CBBTABLE.cbb_usu = USERTABLE.usr_id
	)
GROUP BY ID, NOME
ORDER BY CONTAGEM DESC
